---
mosquitto_acl: |
  user hub
  topic     write     display/+/windspeed
  topic read          display/+/currentwindspeed

  user display
  topic read          display/+/windspeed
  topic     write     display/+/currentwindspeed

mosquitto_conf: |
  log_dest stdout
  #log_type all

  allow_anonymous false
  acl_file /etc/mosquitto/acl
  password_file /etc/mosquitto/passwd
