ssh_call_home_host: hub.wind.mastensg.net
ssh_call_home_private_key: "{{ vault_ssh_call_home_private_key }}"
ssh_call_home_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDWdtSTBh+4oW5ndYQjP0wkqSpZu/ZybYIqaAcLAJNLGyC64ST3STXigXWZ2Z1yZaPWB/LNc8d1ngWlVNKJihHLcsiGJrXp0rZfVmTPh7t30ObgNtPhiZWcNSRZmc4cWCUEGzyPsf2oM3zdnMeIIuSilpfNbOHhYXsMlWu5TxS3zteDfMpxSoyeyR0CZoFZFT+7/JsYLyXsKXtb4TbQkkwfIC4sjoNwn5J63JbVgoi5RKKT9YTldFz5RGS/jWMQutUUV2vFcEIsT/RLzDWxOqb0hLous1hy69Alp70/EZ0H+UqqlNtIrdMqM2yn3IkgkVcfrbKRAg5XszC+gwhTkz0f ssh-call-home@device
ssh_call_home_user: ssh-call-home
