- name: Display firmware
  tags: display-firmware
  block:
  - name: Install system dependencies
    tags: apt
    apt:
      name:
      - python3-pip
      - python-setuptools
      - virtualenv
      - rsync

      # wp_visuals
      - autoconf
      - libtool
      - libcairo2-dev
      - libfreetype6-dev
      - libinput-dev
      - libzmq3-dev

      # gust_gui
      - python3-tk
  - name: unprivileged user
    user:
      name: display
      state: present
      groups: gpio,dialout,video
  - name: firmware root dir
    file:
      path: /opt/windmachine/firmware
      owner: display
      group: display
      state: directory
  - name: Copy firmware code
    synchronize:
      src: '../../firmware/'
      dest: /opt/windmachine/firmware
      delete: yes
      archive: yes
  - name: Copy fonts archive
    tags: fonts
    copy:
      src: opt/windmachine/equinor_fonts.tar.gz
      dest: /opt/windmachine/equinor_fonts.tar.gz
      owner: display
      group: display
  - name: Extract fonts archive
    tags: fonts
    unarchive:
      src: /opt/windmachine/equinor_fonts.tar.gz
      dest: /opt/windmachine/
      owner: display
      group: display
      remote_src: yes
  - name: Set permissions
    file:
      path: /opt/windmachine
      recurse: true
      owner: display
      group: display
  - name: Install Python packages
    pip:
      chdir: '/opt/windmachine/firmware'
      requirements: './requirements.txt'
      virtualenv: /opt/windmachine/venv
      virtualenv_python: '/usr/bin/python3.5'
  - name: Configure wp_visuals
    tags: visuals
    shell: "sudo -u display ./autogen_vc.sh"
    args:
      chdir: /opt/windmachine/firmware/wp_visuals
  - name: Make wp_visuals
    tags: visuals
    shell: "sudo -u display make -j4"
    args:
      chdir: /opt/windmachine/firmware/wp_visuals
  - name: Service config dir
    tags: systemd
    file:
      path: /etc/windmachine
      state: directory
  - name: Provide settings as environment vars
    tags: systemd
    copy:
      content: |
        MSGFLO_BROKER={{display_broker_url}}
        DISPLAY_PREFIX=display/{{ansible_hostname}}
        WP_FONT_PATH=/opt/windmachine/equinor_fonts/Equinor-Medium.otf
      dest: /etc/windmachine/display.env
  - name: Copy service files
    tags: systemd
    copy:
      src: "etc/systemd/system/{{item}}.service"
      dest: "/etc/systemd/system/{{item}}.service"
    with_items:
      - display-firmata
      - display-forwarder
      - display-gust
      - display-mqtt
      - display-visuals
  - name: Start systemd services
    tags: systemd
    systemd:
      name: "{{item}}"
      state: restarted # TODO, only restart when needed 
      enabled: yes
      daemon_reload: yes # TODO, only restart on need
    with_items:
      - display-firmata
      - display-forwarder
      - display-gust
      - display-mqtt
      - display-visuals


