- name: Display firmware
  tags: display-firmware
  block:
  - name: Install system dependencies
    tags: apt
    apt:
      name:
      - python3-pip
      - python-setuptools
      - virtualenv
      - rsync

      # wp_visuals
      - autoconf
      - libtool
      - libcairo2-dev
      - libfreetype6-dev
      - libinput-dev
      - libzmq3-dev
  - name: unprivileged user
    user:
      name: display
      state: present
      groups: gpio,dialout
  - name: firmware root dir
    file:
      path: /opt/windmachine/firmware
      owner: display
      group: display
      state: directory
  - name: Copy firmware code
    synchronize:
      src: '../../firmware/'
      dest: /opt/windmachine/firmware
      delete: yes
      archive: yes
  - name: Set permissions
    file:
      path: /opt/windmachine
      recurse: true
      owner: display
      group: display
  - name: Install Python packages
    pip:
      chdir: '/opt/windmachine/firmware'
      requirements: './requirements.txt'
      virtualenv: /opt/windmachine/venv
      virtualenv_python: '/usr/bin/python3.5'
  - name: Service config dir
    file:
      path: /etc/windmachine
      state: directory
  - name: Provide settings as environment vars 
    copy:
      content: |
        MSGFLO_BROKER={{display_broker_url}}
        DISPLAY_PREFIX=display/{{ansible_hostname}}
      dest: /etc/windmachine/display.env
  - name: Copy service files
    copy:
      src: "etc/systemd/system/{{item}}.service"
      dest: "/etc/systemd/system/{{item}}.service"
    with_items:
      - display-firmata
      - display-firmware
      - display-forwarder
      - display-gust
  - name: Start systemd services
    systemd:
      name: "{{item}}"
      state: restarted # TODO, only restart when needed 
      enabled: yes
      daemon_reload: yes # TODO, only restart on need
    with_items:
      - display-firmata
      - display-firmware
      - display-forwarder
      - display-gust


