- name: Windportal web
  tags: windportal_web
  block:
  - name: Install system dependencies
    tags: apt
    apt:
      name:
      - python3-pip
      - python-setuptools
      - virtualenv
      - rsync
      - nginx

  - name: unprivileged user
    user:
      name: windportal
      state: present

  - name: server root dir
    file:
      path: /opt/windportal/server
      owner: windportal
      group: windportal
      state: directory

  - name: Copy server code
    synchronize:
      src: '../../server/'
      dest: /opt/windportal/server
      delete: yes
      archive: yes

  - name: htpasswd
    tags: nginx
    no_log: yes
    notify: restart nginx
    copy:
      content: "{{ windportal_web_htpasswd }}"
      dest: /opt/windportal/htpasswd

  - name: sites-available
    tags: nginx
    notify: restart nginx
    copy:
      src: etc/nginx/sites-available/default
      dest: /etc/nginx/sites-available/default

  - name: web root
    tags: nginx
    file:
      path: /opt/windportal/html
      state: directory

  - name: Set permissions
    file:
      path: /opt/windportal
      recurse: true
      owner: windportal
      group: windportal

  - name: Install Python packages
    pip:
      chdir: '/opt/windportal/server'
      requirements: './requirements.txt'
      virtualenv: /opt/windportal/venv
      virtualenv_python: '/usr/bin/python3.5'

  - name: Service config dir
    tags: systemd
    file:
      path: /etc/windportal
      state: directory

  - name: Provide settings as environment vars
    tags: systemd
    copy:
      content: |
        BROKER_URL={{hub_broker_url}}
        FETCH_INTERVAL=600
      dest: /etc/windportal/web.env

  - name: Copy service files
    tags: systemd
    copy:
      src: "etc/systemd/system/{{item}}.service"
      dest: "/etc/systemd/system/{{item}}.service"
    with_items:
      - windportal_web

  - name: Restart systemd services
    tags: systemd
    systemd:
      name: "{{item}}"
      state: restarted # TODO, only restart when needed 
      enabled: yes
      daemon_reload: yes # TODO, only restart on need
    with_items:
      - windportal_web
